name: RDP

on:
  schedule:
    - cron: "40 * * * *"
  workflow_dispatch:

jobs:
  rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Ngrok Tunnel Script
      run: |
        powershell.exe -ExecutionPolicy Bypass -File .\rdp.ps1
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_ID }}
