name: Ngrok and Notify Telegram

on:
  push:
    branches:
      - main

jobs:
  rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Ngrok Tunnel Script
      run: |
        powershell.exe -ExecutionPolicy Bypass -File .\rdp.ps1
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}