name: RDP

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Verify TELEGRAM_CHAT_IDS
        run: |
          Write-Host "TELEGRAM_CHAT_IDS from environment: $Env:TELEGRAM_CHAT_IDS"
        env:
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}