name: RDP

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Debugging Chat IDs
        run: |
          Write-Host "Raw TELEGRAM_CHAT_IDS: $Env:TELEGRAM_CHAT_IDS"
          $chatIds = $Env:TELEGRAM_CHAT_IDS -split "," | ForEach-Object { $_.Trim() }
          Write-Host "Parsed Chat IDs: $($chatIds -join ',')"
        env:
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}