name: Playitgg

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Playit.gg
      run: |
        Invoke-WebRequest https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe -OutFile playit.exe
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Check Playit version
      run: .\playit.exe --version
    - name: Create Tunnel with Playit.gg
      run: |
        Start-Process -FilePath .\playit.exe -ArgumentList "tunnel", "create", "--protocol", "tcp", "--port", "3389" -NoNewWindow
        Start-Sleep -Seconds 5 # Allow Playit to start

        # Fetch the public Playit.gg URL
        $playitUrl = Invoke-RestMethod -Uri http://localhost:8080/api/tunnels | 
                    Select-Object -ExpandProperty tunnels | 
                    Select-Object -First 1 | 
                    Select-Object -ExpandProperty public_url -ErrorAction SilentlyContinue

        # Retrieve secrets from environment
        $botToken = $Env:TELEGRAM_BOT_TOKEN
        $chatId = $Env:TELEGRAM_CHAT_ID

        $urlWithoutProtocol = $playitUrl -replace "^tcp://", ""
        $UrlPort = $urlWithoutProtocol.Split(":")[-1]
        $urlWithoutPort = $urlWithoutProtocol -replace ":\d+$", ""
        $message = "
        $urlWithoutPort
        $UrlPort
        "

        # Send the Playit.gg URL to Telegram
        Invoke-RestMethod -Uri "https://api.telegram.org/bot$botToken/sendMessage" `
          -Method Post `
          -ContentType "application/json" `
          -Body (@{chat_id=$chatId; text=$message} | ConvertTo-Json)

        # Keep Playit running
        Write-Host "Playit.gg tunnel is running. Press Ctrl+C to exit."
        while ($true) { Start-Sleep -Seconds 10 }
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
